[2022-11-06 14:05:29,537] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xetra_DAG.run_xetra_etl scheduled__2022-11-04T14:00:00+00:00 [queued]>
[2022-11-06 14:05:29,571] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: xetra_DAG.run_xetra_etl scheduled__2022-11-04T14:00:00+00:00 [queued]>
[2022-11-06 14:05:29,573] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-11-06 14:05:29,574] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-11-06 14:05:29,576] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-11-06 14:05:29,654] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): run_xetra_etl> on 2022-11-04 14:00:00+00:00
[2022-11-06 14:05:29,670] {standard_task_runner.py:52} INFO - Started process 154 to run task
[2022-11-06 14:05:29,696] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'xetra_DAG', 'run_xetra_etl', 'scheduled__2022-11-04T14:00:00+00:00', '--job-id', '154', '--raw', '--subdir', 'DAGS_FOLDER/xetra_DAG.py', '--cfg-path', '/tmp/tmpge27i2_t', '--error-file', '/tmp/tmpp5jxarkw']
[2022-11-06 14:05:29,699] {standard_task_runner.py:80} INFO - Job 154: Subtask run_xetra_etl
[2022-11-06 14:05:30,271] {task_command.py:369} INFO - Running <TaskInstance: xetra_DAG.run_xetra_etl scheduled__2022-11-04T14:00:00+00:00 [running]> on host 0163e0790208
[2022-11-06 14:05:30,684] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=xetra_DAG
AIRFLOW_CTX_TASK_ID=run_xetra_etl
AIRFLOW_CTX_EXECUTION_DATE=2022-11-04T14:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-04T14:00:00+00:00
[2022-11-06 14:06:02,297] {python.py:173} INFO - Done. Returned value was: None
[2022-11-06 14:06:02,286] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=xetra_DAG, task_id=run_xetra_etl, execution_date=20221104T140000, start_date=20221106T140529, end_date=20221106T140602
[2022-11-06 14:06:05,604] {local_task_job.py:221} WARNING - State of this instance has been externally set to success. Terminating instance.
